import { useEffect, useState } from "react";
import { Button, Input, PasswordInput, OTPInput } from "../../components/ui";
import { errorMessage, postJson } from "./api";

export function LoginPage() {
	const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [challengeId, setChallengeId] = useState(""); const [error, setError] = useState(""); const [resendIn, setResendIn] = useState(30);
	const verifying = Boolean(challengeId);
	useEffect(() => { if (!verifying || resendIn <= 0) return; const timer = window.setTimeout(() => setResendIn((value) => value - 1), 1000); return () => window.clearTimeout(timer); }, [verifying, resendIn]);
	async function signIn() { setError(""); try { const response = await postJson<{ challengeId: string }>("/api/login/password", { email, password }); setChallengeId(response.challengeId); setResendIn(30); } catch (reason) { setError(errorMessage(reason instanceof Error ? reason.message : "REQUEST_FAILED")); } }
	async function verify() { setError(""); try { const response = await postJson<{ role?: string }>("/api/otp/verify", { challengeId, code, purpose: "LOGIN" }); const destination = response.role === "DEALER" ? "/products" : "/control"; window.history.replaceState({}, "", destination); window.dispatchEvent(new PopStateEvent("popstate")); } catch (reason) { setError(errorMessage(reason instanceof Error ? reason.message : "REQUEST_FAILED")); } }
	async function resend() { setError(""); try { const response = await postJson<{ challengeId: string }>("/api/otp/resend", { challengeId }); setChallengeId(response.challengeId); setResendIn(30); } catch (reason) { setError(errorMessage(reason instanceof Error ? reason.message : "REQUEST_FAILED")); } }
	if (verifying) return <section className="auth-page"><div className="auth-kicker">Sign-in check <span>02 / 02</span></div><h1>Confirm your sign-in</h1><p className="auth-intro">Enter the code sent to your email before we open your dealer workspace.</p><OTPInput value={code} onChange={setCode} /><Button full disabled={code.length !== 6} onClick={verify}>Confirm sign-in</Button><button className="text-action" type="button" disabled={resendIn > 0} onClick={resend}>{resendIn > 0 ? `Resend available in ${resendIn}s` : "Resend code"}</button>{error && <p className="form-error" role="alert">{error}</p>}</section>;
	return <section className="auth-page"><div className="auth-kicker">Dealer sign in <span>01 / 02</span></div><h1>Welcome back.</h1><p className="auth-intro">Use your dealer email and password. We will ask for a fresh verification code next.</p><label htmlFor="login-email">Email</label><Input id="login-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /><label htmlFor="login-password">Password</label><PasswordInput id="login-password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" /><Button full disabled={!email || !password} onClick={signIn}>Continue</Button>{error && <p className="form-error" role="alert">{error}</p>}<p className="auth-switch">New to the pilot? <a href="/activate">Activate your dealership</a></p></section>;
}
